
CREATE TABLE usuarios (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    nombre varchar(50) NOT NULL,
    username VARCHAR(50) NOT NULL,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULL
);

ALTER TABLE usuarios ADD CONSTRAINT pk_usuarios PRIMARY KEY (id);

CREATE TABLE productos (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    nombre VARCHAR(100) NOT NULL,
    precio DECIMAL(10, 2) NOT NULL,
    descripcion VARCHAR(255)
);

ALTER TABLE productos ADD CONSTRAINT pk_productos PRIMARY KEY (id);

CREATE TABLE compras (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    user_id NUMBER NOT NULL,
    product_id NUMBER NOT NULL,
    cantidad NUMBER NOT NULL,
    fecha_compra TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES usuarios(id),
    CONSTRAINT fk_product FOREIGN KEY (product_id) REFERENCES productos(id)
);